server:
   port: 8282
   

# spring:
#    security:
#       user:
#          name: maxx123
#          password: abc123
#          roles: ADMIN, USER
# security:
#    oauth2:
#       client:
#          client-id: mobile
#          client-secret: pin
#          access-token-validity-seconds: 3600
#          authorized-grant-types: refresh_token,authorization_code,client_credentials
#          scope: READ,WRITE
         